"""Render one accepted world as a `.pyi` module stub.

A world is discovered at runtime, so an editor and a model both see `Any` where
the instance's own vocabulary is. This writes that vocabulary down as types at
exactly one coordinate: the kinds it nests, the Subject IDs that can be spelled
as attributes, every predicate, and each enum member a literal schema names.

The stub is a read, not a pin. It carries the coordinate it was generated at in
its header, and is byte-identical for the same world, so regenerating after an
activation shows the vocabulary movement as an ordinary diff.
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import TYPE_CHECKING

from cruxible_client.authoring.world import (
    KindNamespace,
    WorldClaimType,
    _is_identifier,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from cruxible_client.authoring.world import World, _Node

STUB_HEADER_TAG = "playbill-world-stub-v1"


def _class_name(path: str) -> str:
    """Return a collision-free class name for one dotted world path.

    A dot becomes a double underscore, which no segment can contain, so
    `sec.vuln` and `sec_vuln` never claim the same name.
    """

    return "_W_" + path.replace(".", "__")


def _sorted(values: Iterable[str]) -> list[str]:
    return sorted(values, key=lambda item: item.encode("utf-8"))


def _predicate_block(world: World, node: _Node) -> list[str]:
    claim_type = world.claim_type(node.path)
    assert isinstance(claim_type, WorldClaimType)
    lines = [f"class {_class_name(node.path)}(WorldClaimType):"]
    lines.append(f'    """{node.path}"""')
    lines.append("")
    lines.append(
        f"    # object_kind={claim_type.object_kind.value}"
        f" cardinality={claim_type.cardinality.value}"
        f" referent_sensitivity={claim_type.referent_sensitivity.value}"
    )
    lines.append(
        "    # permitted_roles=" + ",".join(role.value for role in claim_type.permitted_roles)
    )
    lines.append("    # allowed_subject_kinds=" + ",".join(claim_type.allowed_subject_kinds))
    if claim_type.allowed_object_subject_kinds:
        lines.append(
            "    # allowed_object_subject_kinds="
            + ",".join(claim_type.allowed_object_subject_kinds)
        )
    body: list[str] = []
    for child in _sorted(node.children):
        body.append(f"    {child}: {_class_name(node.children[child].path)}")
    for member in _sorted(claim_type.members):
        if _is_identifier(member) and member not in node.children:
            body.append(f"    {member}: LiteralValue")
    lines.extend(body or ["    ..."])
    return lines


def _namespace_block(world: World, node: _Node) -> list[str]:
    lines = [f"class {_class_name(node.path)}(KindNamespace):"]
    lines.append(f'    """{node.path}"""')
    lines.append("")
    body: list[str] = []
    for child in _sorted(node.children):
        body.append(f"    {child}: {_class_name(node.children[child].path)}")
    if node.subject_kind:
        namespace = KindNamespace(world, node)
        for subject_id in _sorted(namespace.subject_ids):
            if _is_identifier(subject_id) and subject_id not in node.children:
                body.append(f"    {subject_id}: WorldSubject")
    lines.extend(body or ["    ..."])
    return lines


def _blocks(world: World, node: _Node) -> list[list[str]]:
    """Emit every descendant block, children before the parent that names them."""

    blocks: list[list[str]] = []
    for name in _sorted(node.children):
        blocks.extend(_blocks(world, node.children[name]))
    if not node.path:
        return blocks
    if node.structure is not None:
        blocks.append(_predicate_block(world, node))
    else:
        blocks.append(_namespace_block(world, node))
    return blocks


def render_world_stub(world: World) -> str:
    """Return the `.pyi` source for one world, byte-identical per coordinate."""

    coordinate = world.coordinate
    lines = [
        f"# {STUB_HEADER_TAG}: generated by `cruxible playbill world stub`.",
        "# Accepted coordinate this world was read at:",
        f"#   git_oid          {coordinate.git_oid}",
        f"#   semantic_root    {coordinate.semantic_root}",
        f"#   generation_root  {coordinate.generation_root}",
        f"#   compiler_digest  {coordinate.compiler_digest}",
        "# Regenerate after every activation. A stub types one coordinate; it",
        "# carries no authority over the next one.",
        "",
        "from cruxible_client.authoring.sdk_types import LiteralValue",
        "from cruxible_client.authoring.world import (",
        "    KindNamespace,",
        "    World as _AcceptedWorld,",
        "    WorldClaimType,",
        "    WorldSubject,",
        ")",
        "",
    ]
    for block in _blocks(world, world._root):
        lines.extend(block)
        lines.append("")
    lines.append("class World(_AcceptedWorld):")
    lines.append('    """The accepted vocabulary at the coordinate in this header."""')
    lines.append("")
    root_body = [
        f"    {name}: {_class_name(world._root.children[name].path)}"
        for name in _sorted(world._root.children)
    ]
    lines.extend(root_body or ["    ..."])
    lines.append("")
    return "\n".join(lines)


__all__ = ["STUB_HEADER_TAG", "render_world_stub"]
