"""Opt-in managed Playbill instance initialization, reopening, and inspection."""

from __future__ import annotations

import json
import os
import secrets
import shutil
import stat
from collections.abc import Sequence
from pathlib import Path

from pydantic import ValidationError

from cruxible_core.playbill.assembler import ProjectionAssembler, ProjectionCrashHook
from cruxible_core.playbill.bootstrap import VerifiedGenesis, prepare_genesis, verify_genesis
from cruxible_core.playbill.canonical import canonical_bytes
from cruxible_core.playbill.cas import CasObjectMetadata, ContentAddressedBodyStore
from cruxible_core.playbill.compiler import (
    SUPPORTED_COMPILERS,
    current_compiler_coordinate,
)
from cruxible_core.playbill.errors import (
    PlaybillBootstrapError,
    PlaybillFormatError,
    PlaybillKeyError,
)
from cruxible_core.playbill.git import GitLedger
from cruxible_core.playbill.keys import (
    ALLOWED_SIGNERS_FILE,
    DAEMON_PRIVATE_KEY_FILE,
    DAEMON_PUBLIC_KEY_FILE,
    generate_daemon_key,
    public_key_hex_from_private_file,
    raw_public_key_hex_from_openssh,
)
from cruxible_core.playbill.projection import AcceptedProjectionCoordinate, AssemblerResult
from cruxible_core.playbill.proposals import ProposalEvidenceStore, ProposalService
from cruxible_core.playbill.types import (
    GenesisCoordinate,
    GitObjectFormat,
    OperatingProfile,
    PlaybillDescriptor,
    PlaybillInspection,
    PlaybillTrustRoot,
    PrincipalInspection,
    PrincipalRecord,
    RecoveryPosture,
    StorageLayout,
    initial_authority_matrix,
)
from cruxible_core.temporal import format_datetime, utc_now

DESCRIPTOR_FILE = "instance.json"


def _resolved(path: Path) -> Path:
    return path.expanduser().resolve(strict=False)


def _is_within(candidate: Path, root: Path) -> bool:
    return candidate == root or root in candidate.parents


def _fsync_directory(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _exclusive_write(path: Path, content: bytes, mode: int = 0o600) -> None:
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, mode)
    try:
        view = memoryview(content)
        while view:
            written = os.write(descriptor, view)
            view = view[written:]
        os.fsync(descriptor)
    finally:
        os.close(descriptor)
    os.chmod(path, mode)
    _fsync_directory(path.parent)


def _validate_client_principals(
    records: Sequence[PrincipalRecord],
    *,
    operating_profile: OperatingProfile,
) -> tuple[tuple[PrincipalRecord, ...], RecoveryPosture]:
    ordered = tuple(sorted(records, key=lambda record: record.principal_id))
    identifiers = [record.principal_id for record in ordered]
    if identifiers != sorted(set(identifiers)):
        raise PlaybillBootstrapError("bootstrap client principals must be unique")
    if not ordered:
        raise PlaybillBootstrapError("bootstrap requires at least one client principal")
    if any(record.principal_id == "daemon" for record in ordered):
        raise PlaybillBootstrapError("the daemon principal is generated by the instance")
    if any(record.status != "active" for record in ordered):
        raise PlaybillBootstrapError("bootstrap client principals must begin active")
    if any("daemon" in record.authority_roles for record in ordered):
        raise PlaybillBootstrapError("client principals cannot carry daemon authority")
    if not any("owner" in record.authority_roles for record in ordered):
        raise PlaybillBootstrapError("bootstrap requires at least one owner principal")
    recovery_configured = any("recovery" in record.authority_roles for record in ordered)
    if operating_profile == "cloud" and not recovery_configured:
        raise PlaybillBootstrapError("cloud Playbill instances require a recovery principal")
    posture: RecoveryPosture = (
        "recovery-configured" if recovery_configured else "narrowed-no-recovery"
    )
    return ordered, posture


class PlaybillInstance:
    """A verified opt-in Playbill substrate rooted outside agent workspaces."""

    def __init__(
        self,
        root: Path,
        descriptor: PlaybillDescriptor,
        trust_root: PlaybillTrustRoot,
        ledger: GitLedger,
        verified_genesis: VerifiedGenesis,
    ) -> None:
        self.root = root
        self.descriptor = descriptor
        self.trust_root = trust_root
        self._ledger = ledger
        self._verified_genesis = verified_genesis

    @classmethod
    def initialize(
        cls,
        root: Path,
        *,
        instance_id: str,
        client_principals: Sequence[PrincipalRecord],
        workspace_roots: Sequence[Path],
        git_object_format: GitObjectFormat = "sha256",
        operating_profile: OperatingProfile = "local",
        timestamp: str | None = None,
    ) -> "PlaybillInstance":
        """Create and reopen one managed instance from explicit bootstrap inputs."""

        if not root.is_absolute():
            raise PlaybillBootstrapError("managed Playbill root must be absolute")
        managed_root = _resolved(root)
        for workspace in workspace_roots:
            if _is_within(managed_root, _resolved(workspace)):
                raise PlaybillBootstrapError(
                    "managed Playbill root must be outside every declared agent workspace"
                )
        if managed_root.exists():
            raise PlaybillBootstrapError(f"managed Playbill root already exists: {managed_root}")

        clients, recovery_posture = _validate_client_principals(
            client_principals,
            operating_profile=operating_profile,
        )
        layout = StorageLayout()
        managed_root.parent.mkdir(parents=True, exist_ok=True)
        managed_root.mkdir(mode=0o700)
        os.chmod(managed_root, 0o700)
        try:
            for relative in (
                layout.projections,
                layout.cas,
                layout.exhaust,
                layout.leases,
            ):
                directory = managed_root / relative
                directory.mkdir(mode=0o700)
                os.chmod(directory, 0o700)

            credentials = managed_root / layout.credentials
            daemon_material = generate_daemon_key(credentials)
            principals = tuple(
                sorted((daemon_material.principal, *clients), key=lambda item: item.principal_id)
            )
            trust_root = PlaybillTrustRoot(
                instance_id=instance_id,
                daemon_public_key=daemon_material.principal.public_key,
                principals=principals,
            )

            ledger = GitLedger.initialize(
                managed_root / layout.ledger,
                object_format=git_object_format,
                signing_key_path=daemon_material.private_key_path,
                allowed_signers_path=credentials / ALLOWED_SIGNERS_FILE,
            )
            commit_timestamp = timestamp or format_datetime(utc_now())
            if commit_timestamp is None:
                raise PlaybillBootstrapError("failed to produce a canonical bootstrap timestamp")
            verified = prepare_genesis(
                ledger,
                trust_root=trust_root,
                timestamp=commit_timestamp,
            )
            descriptor = PlaybillDescriptor(
                instance_id=instance_id,
                git_object_format=git_object_format,
                daemon_public_key=trust_root.daemon_public_key,
                compiler=current_compiler_coordinate(),
                authority=initial_authority_matrix(),
                operating_profile=operating_profile,
                recovery_posture=recovery_posture,
                storage=layout,
                genesis=GenesisCoordinate(
                    git_oid=verified.oid,
                    bootstrap_root=verified.bootstrap_root.tagged,
                    semantic_root=verified.semantic_root.tagged,
                    generation_root=verified.generation_root.tagged,
                ),
            )
            _exclusive_write(
                managed_root / DESCRIPTOR_FILE,
                canonical_bytes(descriptor.model_dump(mode="json")) + b"\n",
            )
            _fsync_directory(managed_root)
            return cls.open(managed_root, trust_root=trust_root)
        except BaseException:
            # `managed_root` was proven absent and created by this invocation.
            # Removing this exact incomplete target cannot affect prior user data.
            shutil.rmtree(managed_root)
            raise

    @classmethod
    def open(cls, root: Path, *, trust_root: PlaybillTrustRoot) -> "PlaybillInstance":
        """Reopen only after replaying descriptor, key, signature, and both roots."""

        managed_root = _resolved(root)
        descriptor_path = managed_root / DESCRIPTOR_FILE
        if descriptor_path.is_symlink():
            raise PlaybillFormatError("Playbill descriptor may not be a symlink")
        try:
            raw_descriptor = descriptor_path.read_bytes()
            payload = json.loads(raw_descriptor)
        except (OSError, json.JSONDecodeError, UnicodeDecodeError) as exc:
            raise PlaybillFormatError("Playbill descriptor is missing or malformed") from exc
        if not isinstance(payload, dict):
            raise PlaybillFormatError("Playbill descriptor must be a JSON object")
        if payload.get("format_version") != 1 or payload.get("tag") != "playbill-instance-v1":
            raise PlaybillFormatError(
                "unsupported Playbill descriptor version; upgrade or use an explicit fork/import"
            )
        if payload.get("git_object_format") not in {"sha1", "sha256"}:
            raise PlaybillFormatError(
                "unsupported Playbill Git object format; use an explicit fork/import"
            )
        try:
            descriptor = PlaybillDescriptor.model_validate(payload)
        except ValidationError as exc:
            raise PlaybillFormatError("Playbill descriptor failed strict validation") from exc
        if canonical_bytes(descriptor.model_dump(mode="json")) + b"\n" != raw_descriptor:
            raise PlaybillFormatError("Playbill descriptor is not canonical")
        if descriptor.instance_id != trust_root.instance_id:
            raise PlaybillBootstrapError("descriptor instance ID differs from trust root")
        if descriptor.daemon_public_key != trust_root.daemon_public_key:
            raise PlaybillBootstrapError("descriptor daemon key differs from trust root")
        if descriptor.compiler not in SUPPORTED_COMPILERS:
            raise PlaybillFormatError("descriptor compiler coordinate is unsupported")
        if descriptor.authority != initial_authority_matrix():
            raise PlaybillBootstrapError(
                "PB-A descriptor authority matrix differs from the initial migration state"
            )
        if descriptor.storage != StorageLayout():
            raise PlaybillFormatError(
                "descriptor storage layout is unsupported; use an explicit fork/import"
            )
        recovery_configured = any(
            "recovery" in principal.authority_roles for principal in trust_root.principals
        )
        expected_recovery: RecoveryPosture = (
            "recovery-configured" if recovery_configured else "narrowed-no-recovery"
        )
        if descriptor.recovery_posture != expected_recovery:
            raise PlaybillBootstrapError(
                "descriptor recovery posture differs from bootstrap principals"
            )

        paths = cls._validated_paths(managed_root, descriptor.storage)
        private_key_path = paths["credentials"] / DAEMON_PRIVATE_KEY_FILE
        public_key_path = paths["credentials"] / DAEMON_PUBLIC_KEY_FILE
        allowed_signers_path = paths["credentials"] / ALLOWED_SIGNERS_FILE
        for name, path in (
            ("daemon private key", private_key_path),
            ("daemon public key", public_key_path),
            ("allowed signers", allowed_signers_path),
        ):
            if path.is_symlink() or not path.is_file():
                raise PlaybillKeyError(f"managed {name} must be a regular file")
        if public_key_hex_from_private_file(private_key_path) != trust_root.daemon_public_key:
            raise PlaybillKeyError("daemon private key does not match the trust root")
        if (
            raw_public_key_hex_from_openssh(public_key_path.read_bytes())
            != trust_root.daemon_public_key
        ):
            raise PlaybillKeyError("daemon public key does not match the trust root")
        private_mode = stat.S_IMODE(private_key_path.stat().st_mode)
        if private_mode & 0o077:
            raise PlaybillKeyError("daemon private key permissions expose group/world access")

        ledger = GitLedger(
            paths["ledger"],
            signing_key_path=private_key_path,
            allowed_signers_path=allowed_signers_path,
        )
        if ledger.object_format() != descriptor.git_object_format:
            raise PlaybillFormatError(
                "ledger object format differs from descriptor; object-format changes require "
                "an explicit fork/import"
            )
        main_oid = ledger.read_main()
        if main_oid != descriptor.genesis.git_oid:
            raise PlaybillBootstrapError("PB-A instance main differs from recorded genesis")
        verified = verify_genesis(ledger, main_oid, trust_root=trust_root)
        expected = GenesisCoordinate(
            git_oid=verified.oid,
            bootstrap_root=verified.bootstrap_root.tagged,
            semantic_root=verified.semantic_root.tagged,
            generation_root=verified.generation_root.tagged,
        )
        if expected != descriptor.genesis:
            raise PlaybillBootstrapError("recorded genesis coordinates do not reproduce")
        return cls(managed_root, descriptor, trust_root, ledger, verified)

    @staticmethod
    def _validated_paths(root: Path, layout: StorageLayout) -> dict[str, Path]:
        paths: dict[str, Path] = {}
        for name, relative in layout.model_dump().items():
            path = root / relative
            if path.is_symlink():
                raise PlaybillFormatError(f"managed storage path may not be a symlink: {name}")
            try:
                resolved = path.resolve(strict=True)
            except OSError as exc:
                raise PlaybillFormatError(f"managed storage path is missing: {name}") from exc
            if not _is_within(resolved, root) or not resolved.is_dir():
                raise PlaybillFormatError(f"managed storage path escapes instance root: {name}")
            paths[name] = resolved
        return paths

    def inspect(self) -> PlaybillInspection:
        """Return public coordinates and custody posture without key locations."""

        paths = self._validated_paths(self.root, self.descriptor.storage)
        principals = tuple(
            PrincipalInspection(
                principal_id=record.principal_id,
                algorithm=record.algorithm,
                authority_roles=record.authority_roles,
                status=record.status,
                public_key_digest=record.public_key_digest,
            )
            for record in self._verified_genesis.principals
        )
        storage_directories = {
            name: str(path) for name, path in paths.items() if name != "credentials"
        }
        return PlaybillInspection(
            descriptor_tag=self.descriptor.tag,
            format_version=self.descriptor.format_version,
            instance_id=self.descriptor.instance_id,
            git_object_format=self.descriptor.git_object_format,
            head_oid=self._verified_genesis.oid,
            bootstrap_root=self._verified_genesis.bootstrap_root.tagged,
            semantic_root=self._verified_genesis.semantic_root.tagged,
            generation_root=self._verified_genesis.generation_root.tagged,
            compiler=self.descriptor.compiler,
            authority=self.descriptor.authority,
            operating_profile=self.descriptor.operating_profile,
            recovery_posture=self.descriptor.recovery_posture,
            principals=principals,
            managed_root=str(self.root),
            storage_directories=storage_directories,
            daemon_private_key_present=(paths["credentials"] / DAEMON_PRIVATE_KEY_FILE).is_file(),
        )

    def accepted_coordinate(self) -> AcceptedProjectionCoordinate:
        """Return the verified accepted coordinate without consulting proposal refs."""

        paths = self._validated_paths(self.root, self.descriptor.storage)
        return AcceptedProjectionCoordinate(
            instance_id=self.descriptor.instance_id,
            repository_path=str(paths["ledger"]),
            git_object_format=self.descriptor.git_object_format,
            git_oid=self._verified_genesis.oid,
            semantic_root=self._verified_genesis.semantic_root.tagged,
            generation_root=self._verified_genesis.generation_root.tagged,
            compiler=self.descriptor.compiler,
        )

    def projection_assembler(self) -> ProjectionAssembler:
        """Bind PB-B's internal assembler to this already-verified generation."""

        paths = self._validated_paths(self.root, self.descriptor.storage)
        return ProjectionAssembler(
            self._ledger,
            accepted=self.accepted_coordinate(),
            publication_directory=paths["projections"],
            bodies=ContentAddressedBodyStore(paths["cas"]),
        )

    def body_store(self) -> ContentAddressedBodyStore:
        """Return PB-C's inert, access-controlled content-addressed body store."""

        paths = self._validated_paths(self.root, self.descriptor.storage)
        return ContentAddressedBodyStore(paths["cas"])

    def store_document_body(self, content: bytes) -> CasObjectMetadata:
        """Persist inert bytes without proposing or changing accepted state."""

        return self.body_store().store(content)

    def proposal_service(self) -> ProposalService:
        """Bind PB-C proposal evaluation to authenticated main and inert storage."""

        paths = self._validated_paths(self.root, self.descriptor.storage)
        return ProposalService(
            self._ledger,
            accepted=self.accepted_coordinate(),
            bodies=ContentAddressedBodyStore(paths["cas"]),
            evidence=ProposalEvidenceStore(paths["exhaust"]),
        )

    def assemble_projection(
        self,
        *,
        crash_hook: ProjectionCrashHook | None = None,
    ) -> AssemblerResult:
        """Build and publish the current verified generation for internal serving."""

        assembler = self.projection_assembler()
        staging = assembler.publication_directory / f".stage-{secrets.token_hex(12)}"
        return assembler.assemble(
            assembler.request(output_staging_directory=staging),
            crash_hook=crash_hook,
        )


__all__ = ["DESCRIPTOR_FILE", "PlaybillInstance"]
