"""Opt-in managed Playbill instance initialization, reopening, and inspection."""

from __future__ import annotations

import json
import os
import secrets
import shutil
import stat
from collections.abc import Callable, Sequence
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, cast

from pydantic import ValidationError

from cruxible_client.contracts.approval_policy import (
    APPROVAL_POLICY_PATH,
    ApprovalPolicyV1,
    parse_approval_policy,
)
from cruxible_client.contracts.attestations import ApprovalSubmission
from cruxible_client.contracts.candidates import CandidateRecordAnyVersion
from cruxible_client.contracts.canonical import canonical_bytes
from cruxible_client.contracts.errors import (
    PlaybillBootstrapError,
    PlaybillFormatError,
    PlaybillKeyError,
)
from cruxible_client.contracts.temporal import format_datetime, utc_now
from cruxible_client.contracts.types import (
    GenesisCoordinate,
    GitObjectFormat,
    OperatingProfile,
    PlaybillDescriptor,
    PlaybillInspection,
    PlaybillTrustRoot,
    PrincipalInspection,
    PrincipalRecord,
    RecoveryPosture,
    StorageLayout,
    initial_authority_matrix,
)
from cruxible_client.contracts.workspace_advertisement import (
    NOT_ATTACHED_ADVERTISEMENT,
    PlaybillWorkspaceAdvertisement,
)
from cruxible_core.playbill.activation import ActivationPublisher
from cruxible_core.playbill.assembler import ProjectionAssembler, ProjectionCrashHook
from cruxible_core.playbill.bootstrap import (
    VerifiedGenesis,
    prepare_genesis,
    seeded_procedure_runtime_policy,
    verify_genesis,
)
from cruxible_core.playbill.cas import CasObjectMetadata, ContentAddressedBodyStore
from cruxible_core.playbill.checkpoints import (
    CHECKPOINT_DIRECTORY,
    DEFAULT_CHECKPOINT_INTERVAL,
)
from cruxible_core.playbill.compiler import (
    SUPPORTED_COMPILERS,
    current_compiler_coordinate,
)
from cruxible_core.playbill.git import GitLedger
from cruxible_core.playbill.keys import (
    ALLOWED_SIGNERS_FILE,
    DAEMON_PRIVATE_KEY_FILE,
    DAEMON_PUBLIC_KEY_FILE,
    generate_daemon_key,
    public_key_hex_from_private_file,
    raw_public_key_hex_from_openssh,
)
from cruxible_core.playbill.projection import (
    AcceptedCoordinate,
    AcceptedProjectionCoordinate,
    AssemblerResult,
    projection_manifest_name,
)
from cruxible_core.playbill.proposal_evidence import ProposalEvidenceStore
from cruxible_core.playbill.proposals import (
    ExhaustPromotionVerifierProtocol,
    ProposalService,
)
from cruxible_core.playbill.recovery import (
    RecoveredGeneration,
    RecoveredInstanceState,
    recover_instance,
)
from cruxible_core.playbill.review_operational import ReviewOperationalStore
from cruxible_core.playbill.serving import bind_current_projection
from cruxible_core.playbill.settlement import (
    ChangeActorBinding,
    VerifiedGenerationBundle,
    prepare_generation,
)
from cruxible_core.playbill.witness import WitnessSink
from cruxible_core.storage.playbill_projection import ProjectionHandle, bind_projection

if TYPE_CHECKING:
    from cruxible_core.playbill.claim_attestation_store import ClaimAttestationEvidenceStore
    from cruxible_core.playbill.query.backends import ClaimQueryFactsV1

DESCRIPTOR_FILE = "instance.json"


def _resolved(path: Path) -> Path:
    return path.expanduser().resolve(strict=False)


def _is_within(candidate: Path, root: Path) -> bool:
    return candidate == root or root in candidate.parents


def _fsync_directory(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _exclusive_write(path: Path, content: bytes, mode: int = 0o600) -> None:
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, mode)
    try:
        view = memoryview(content)
        while view:
            written = os.write(descriptor, view)
            view = view[written:]
        os.fsync(descriptor)
    finally:
        os.close(descriptor)
    os.chmod(path, mode)
    _fsync_directory(path.parent)


def _validate_client_principals(
    records: Sequence[PrincipalRecord],
) -> tuple[tuple[PrincipalRecord, ...], RecoveryPosture]:
    ordered = tuple(sorted(records, key=lambda record: record.principal_id))
    identifiers = [record.principal_id for record in ordered]
    if identifiers != sorted(set(identifiers)):
        raise PlaybillBootstrapError("bootstrap client principals must be unique")
    ordinary = [record for record in ordered if record.kind == "ordinary"]
    if len(ordinary) < 1:
        raise PlaybillBootstrapError("bootstrap requires at least one ordinary principal")
    if any(record.principal_id == "daemon" for record in ordered):
        raise PlaybillBootstrapError("the daemon principal is generated by the instance")
    if any(record.status != "active" for record in ordered):
        raise PlaybillBootstrapError("bootstrap client principals must begin active")
    if any(record.kind == "daemon" for record in ordered):
        raise PlaybillBootstrapError("client principals cannot have daemon kind")
    recovery_configured = any(record.kind == "recovery" for record in ordered)
    posture: RecoveryPosture = (
        "recovery-configured" if recovery_configured else "narrowed-no-recovery"
    )
    return ordered, posture


class PlaybillInstance:
    """A verified opt-in Playbill substrate rooted outside agent workspaces."""

    def __init__(
        self,
        root: Path,
        descriptor: PlaybillDescriptor,
        trust_root: PlaybillTrustRoot,
        ledger: GitLedger,
        verified_genesis: VerifiedGenesis,
        recovered: RecoveredInstanceState,
        promotion_verifier: ExhaustPromotionVerifierProtocol | None = None,
    ) -> None:
        self.root = root
        self.descriptor = descriptor
        self.trust_root = trust_root
        self._ledger = ledger
        self._verified_genesis = verified_genesis
        self._recovered = recovered
        self._promotion_verifier = promotion_verifier
        self._claim_attestation_store: ClaimAttestationEvidenceStore | None = None
        self._workspace_advertiser: Callable[[], PlaybillWorkspaceAdvertisement] | None = None

    @staticmethod
    def _accepted_query_facts(
        source: object,
        coordinate: AcceptedProjectionCoordinate,
    ) -> "ClaimQueryFactsV1":
        """Build the one accepted-Claim facts projection for live and replay paths."""

        from cruxible_core.service.playbill_evidence import ClaimReadSourceProtocol
        from cruxible_core.service.playbill_query import build_accepted_query_facts

        return build_accepted_query_facts(
            cast(ClaimReadSourceProtocol, source),
            coordinate=coordinate,
        )

    @classmethod
    def initialize(
        cls,
        root: Path,
        *,
        instance_id: str,
        client_principals: Sequence[PrincipalRecord],
        workspace_roots: Sequence[Path],
        git_object_format: GitObjectFormat = "sha256",
        operating_profile: OperatingProfile = "local",
        require_independent_approval: bool = False,
        timestamp: str | None = None,
        promotion_verifier: ExhaustPromotionVerifierProtocol | None = None,
    ) -> "PlaybillInstance":
        """Create and reopen one managed instance from explicit bootstrap inputs."""

        if not root.is_absolute():
            raise PlaybillBootstrapError("managed Playbill root must be absolute")
        managed_root = _resolved(root)
        for workspace in workspace_roots:
            if _is_within(managed_root, _resolved(workspace)):
                raise PlaybillBootstrapError(
                    "managed Playbill root must be outside every declared agent workspace"
                )
        if managed_root.exists():
            raise PlaybillBootstrapError(f"managed Playbill root already exists: {managed_root}")

        clients, recovery_posture = _validate_client_principals(client_principals)
        if (
            require_independent_approval
            and sum(record.kind == "ordinary" and record.status == "active" for record in clients)
            < 2
        ):
            raise PlaybillBootstrapError(
                "independent approval requires at least two active ordinary principals"
            )
        layout = StorageLayout()
        managed_root.parent.mkdir(parents=True, exist_ok=True)
        managed_root.mkdir(mode=0o700)
        os.chmod(managed_root, 0o700)
        try:
            for relative in (
                layout.projections,
                layout.cas,
                layout.exhaust,
                layout.leases,
            ):
                directory = managed_root / relative
                directory.mkdir(mode=0o700)
                os.chmod(directory, 0o700)

            credentials = managed_root / layout.credentials
            daemon_material = generate_daemon_key(credentials)
            principals = tuple(
                sorted((daemon_material.principal, *clients), key=lambda item: item.principal_id)
            )
            trust_root = PlaybillTrustRoot(
                instance_id=instance_id,
                daemon_public_key=daemon_material.principal.public_key,
                principals=principals,
            )

            ledger = GitLedger.initialize(
                managed_root / layout.ledger,
                object_format=git_object_format,
                signing_key_path=daemon_material.private_key_path,
                allowed_signers_path=credentials / ALLOWED_SIGNERS_FILE,
            )
            commit_timestamp = timestamp or format_datetime(utc_now())
            if commit_timestamp is None:
                raise PlaybillBootstrapError("failed to produce a canonical bootstrap timestamp")
            verified = prepare_genesis(
                ledger,
                trust_root=trust_root,
                approval_policy=ApprovalPolicyV1(
                    mode=(
                        "independent_approval_required"
                        if require_independent_approval
                        else "self_approval_allowed"
                    )
                ),
                procedure_runtime_policy=seeded_procedure_runtime_policy(),
                timestamp=commit_timestamp,
            )
            descriptor = PlaybillDescriptor(
                instance_id=instance_id,
                git_object_format=git_object_format,
                daemon_public_key=trust_root.daemon_public_key,
                compiler=current_compiler_coordinate(),
                authority=initial_authority_matrix(),
                operating_profile=operating_profile,
                recovery_posture=recovery_posture,
                storage=layout,
                genesis=GenesisCoordinate(
                    git_oid=verified.oid,
                    bootstrap_root=verified.bootstrap_root.tagged,
                    semantic_root=verified.semantic_root.tagged,
                    generation_root=verified.generation_root.tagged,
                ),
            )
            _exclusive_write(
                managed_root / DESCRIPTOR_FILE,
                canonical_bytes(descriptor.model_dump(mode="json")) + b"\n",
            )
            _fsync_directory(managed_root)
            return cls.open(
                managed_root,
                trust_root=trust_root,
                promotion_verifier=promotion_verifier,
            )
        except BaseException:
            # `managed_root` was proven absent and created by this invocation.
            # Removing this exact incomplete target cannot affect prior user data.
            shutil.rmtree(managed_root)
            raise

    @classmethod
    def open(
        cls,
        root: Path,
        *,
        trust_root: PlaybillTrustRoot,
        witness: WitnessSink | None = None,
        promotion_verifier: ExhaustPromotionVerifierProtocol | None = None,
    ) -> "PlaybillInstance":
        """Reopen only after replaying descriptor, key, signature, and both roots."""

        managed_root = _resolved(root)
        descriptor_path = managed_root / DESCRIPTOR_FILE
        if descriptor_path.is_symlink():
            raise PlaybillFormatError("Playbill descriptor may not be a symlink")
        try:
            raw_descriptor = descriptor_path.read_bytes()
            payload = json.loads(raw_descriptor)
        except (OSError, json.JSONDecodeError, UnicodeDecodeError) as exc:
            raise PlaybillFormatError("Playbill descriptor is missing or malformed") from exc
        if not isinstance(payload, dict):
            raise PlaybillFormatError("Playbill descriptor must be a JSON object")
        if payload.get("format_version") != 1 or payload.get("tag") != "playbill-instance-v1":
            raise PlaybillFormatError(
                "unsupported Playbill descriptor version; upgrade or use an explicit fork/import"
            )
        if payload.get("git_object_format") not in {"sha1", "sha256"}:
            raise PlaybillFormatError(
                "unsupported Playbill Git object format; use an explicit fork/import"
            )
        try:
            descriptor = PlaybillDescriptor.model_validate(payload)
        except ValidationError as exc:
            raise PlaybillFormatError("Playbill descriptor failed strict validation") from exc
        if canonical_bytes(descriptor.model_dump(mode="json")) + b"\n" != raw_descriptor:
            raise PlaybillFormatError("Playbill descriptor is not canonical")
        if descriptor.instance_id != trust_root.instance_id:
            raise PlaybillBootstrapError("descriptor instance ID differs from trust root")
        if descriptor.daemon_public_key != trust_root.daemon_public_key:
            raise PlaybillBootstrapError("descriptor daemon key differs from trust root")
        if descriptor.compiler not in SUPPORTED_COMPILERS:
            raise PlaybillFormatError("descriptor compiler coordinate is unsupported")
        if descriptor.authority != initial_authority_matrix():
            raise PlaybillBootstrapError(
                "PB-A descriptor authority matrix differs from the initial migration state"
            )
        if descriptor.storage != StorageLayout():
            raise PlaybillFormatError(
                "descriptor storage layout is unsupported; use an explicit fork/import"
            )
        recovery_configured = any(
            principal.kind == "recovery" for principal in trust_root.principals
        )
        expected_recovery: RecoveryPosture = (
            "recovery-configured" if recovery_configured else "narrowed-no-recovery"
        )
        if descriptor.recovery_posture != expected_recovery:
            raise PlaybillBootstrapError(
                "descriptor recovery posture differs from bootstrap principals"
            )

        paths = cls._validated_paths(managed_root, descriptor.storage)
        private_key_path = paths["credentials"] / DAEMON_PRIVATE_KEY_FILE
        public_key_path = paths["credentials"] / DAEMON_PUBLIC_KEY_FILE
        allowed_signers_path = paths["credentials"] / ALLOWED_SIGNERS_FILE
        for name, path in (
            ("daemon private key", private_key_path),
            ("daemon public key", public_key_path),
            ("allowed signers", allowed_signers_path),
        ):
            if path.is_symlink() or not path.is_file():
                raise PlaybillKeyError(f"managed {name} must be a regular file")
        if public_key_hex_from_private_file(private_key_path) != trust_root.daemon_public_key:
            raise PlaybillKeyError("daemon private key does not match the trust root")
        if (
            raw_public_key_hex_from_openssh(public_key_path.read_bytes())
            != trust_root.daemon_public_key
        ):
            raise PlaybillKeyError("daemon public key does not match the trust root")
        private_mode = stat.S_IMODE(private_key_path.stat().st_mode)
        if private_mode & 0o077:
            raise PlaybillKeyError("daemon private key permissions expose group/world access")

        ledger = GitLedger(
            paths["ledger"],
            signing_key_path=private_key_path,
            allowed_signers_path=allowed_signers_path,
        )
        if ledger.object_format() != descriptor.git_object_format:
            raise PlaybillFormatError(
                "ledger object format differs from descriptor; object-format changes require "
                "an explicit fork/import"
            )
        verified = verify_genesis(
            ledger,
            descriptor.genesis.git_oid,
            trust_root=trust_root,
        )
        expected = GenesisCoordinate(
            git_oid=verified.oid,
            bootstrap_root=verified.bootstrap_root.tagged,
            semantic_root=verified.semantic_root.tagged,
            generation_root=verified.generation_root.tagged,
        )
        if expected != descriptor.genesis:
            raise PlaybillBootstrapError("recorded genesis coordinates do not reproduce")
        recovered = recover_instance(
            ledger,
            genesis=verified,
            instance_id=descriptor.instance_id,
            object_format=descriptor.git_object_format,
            compiler=descriptor.compiler,
            publication_directory=paths["projections"],
            bodies=ContentAddressedBodyStore(paths["cas"]),
            witness=witness,
            promotion_verifier=promotion_verifier,
            query_facts_builder=cls._accepted_query_facts,
            checkpoint_directory=cls._checkpoint_directory(managed_root),
        )
        return cls(
            managed_root,
            descriptor,
            trust_root,
            ledger,
            verified,
            recovered,
            promotion_verifier,
        )

    @staticmethod
    def _checkpoint_directory(root: Path) -> Path:
        """Locate the rebuildable checkpoint cache beside the managed storage roots.

        Deliberately not a `StorageLayout` field: the layout is part of the
        frozen `playbill-instance-v1` descriptor preimage, and a disposable local
        cache may never widen an accepted format. The directory is created on
        first write, may be deleted at any time, and `inspect()` never reports it
        as semantic storage.
        """

        return root / CHECKPOINT_DIRECTORY

    @staticmethod
    def _validated_paths(root: Path, layout: StorageLayout) -> dict[str, Path]:
        paths: dict[str, Path] = {}
        for name, relative in layout.model_dump().items():
            path = root / relative
            if path.is_symlink():
                raise PlaybillFormatError(f"managed storage path may not be a symlink: {name}")
            try:
                resolved = path.resolve(strict=True)
            except OSError as exc:
                raise PlaybillFormatError(f"managed storage path is missing: {name}") from exc
            if not _is_within(resolved, root) or not resolved.is_dir():
                raise PlaybillFormatError(f"managed storage path escapes instance root: {name}")
            paths[name] = resolved
        return paths

    def inspect(self) -> PlaybillInspection:
        """Return public coordinates and custody posture without key locations."""

        paths = self._validated_paths(self.root, self.descriptor.storage)
        principals = tuple(
            PrincipalInspection(
                principal_id=record.principal_id,
                algorithm=record.algorithm,
                kind=record.kind,
                status=record.status,
                public_key_digest=record.public_key_digest,
            )
            for record in self._recovered.head.principals.principals
        )
        storage_directories = {
            name: str(path) for name, path in paths.items() if name != "credentials"
        }
        accepted_tree = self.tree_at(self._recovered.head.oid)
        approval_policy = parse_approval_policy(
            accepted_tree[APPROVAL_POLICY_PATH],
            path=APPROVAL_POLICY_PATH,
        )
        return PlaybillInspection(
            descriptor_tag=self.descriptor.tag,
            format_version=self.descriptor.format_version,
            instance_id=self.descriptor.instance_id,
            git_object_format=self.descriptor.git_object_format,
            head_oid=self._recovered.head.oid,
            bootstrap_root=self._verified_genesis.bootstrap_root.tagged,
            semantic_root=self._recovered.head.semantic_root.tagged,
            generation_root=self._recovered.head.generation_root.tagged,
            compiler=self.descriptor.compiler,
            authority=self.descriptor.authority,
            operating_profile=self.descriptor.operating_profile,
            recovery_posture=self.descriptor.recovery_posture,
            approval_policy_mode=approval_policy.mode,
            principals=principals,
            managed_root=str(self.root),
            storage_directories=storage_directories,
            daemon_private_key_present=(paths["credentials"] / DAEMON_PRIVATE_KEY_FILE).is_file(),
        )

    def accepted_coordinate(self) -> AcceptedProjectionCoordinate:
        """Return the verified accepted coordinate without consulting proposal refs."""

        return self._recovered.coordinate

    def _accepted_coordinates_by_sequence(self) -> dict[int, AcceptedCoordinate]:
        """Return replay-proven historical coordinates for stable derived activations."""

        compiler_digest = self.descriptor.compiler.rule_digest
        return {
            generation.sequence: AcceptedCoordinate(
                git_oid=generation.oid,
                semantic_root=generation.semantic_root.tagged,
                generation_root=generation.generation_root.tagged,
                compiler_digest=compiler_digest,
            )
            for generation in self._recovered.history
        }

    def projection_assembler(self) -> ProjectionAssembler:
        """Bind PB-B's internal assembler to this already-verified generation."""

        paths = self._validated_paths(self.root, self.descriptor.storage)
        return ProjectionAssembler(
            self._ledger,
            accepted=self.accepted_coordinate(),
            publication_directory=paths["projections"],
            bodies=ContentAddressedBodyStore(paths["cas"]),
            accepted_coordinates_by_sequence=self._accepted_coordinates_by_sequence(),
        )

    def body_store(self) -> ContentAddressedBodyStore:
        """Return PB-C's inert, access-controlled content-addressed body store."""

        paths = self._validated_paths(self.root, self.descriptor.storage)
        return ContentAddressedBodyStore(
            paths["cas"],
            reservation_root=paths["leases"] / "procedure-material",
        )

    def store_document_body(self, content: bytes) -> CasObjectMetadata:
        """Persist inert bytes without proposing or changing accepted state."""

        return self.body_store().store(content)

    def proposal_service(self) -> ProposalService:
        """Bind PB-C proposal evaluation to authenticated main and inert storage."""

        paths = self._validated_paths(self.root, self.descriptor.storage)
        return ProposalService(
            self._ledger,
            accepted=self.accepted_coordinate(),
            bodies=ContentAddressedBodyStore(paths["cas"]),
            evidence=ProposalEvidenceStore(paths["exhaust"]),
            current_coordinate=self.accepted_coordinate,
            promotion_verifier=self._promotion_verifier,
            query_facts_provider=lambda coordinate: self._accepted_query_facts(self, coordinate),
            workspace_advertiser=self.advertise_workspace,
        )

    def bind_workspace_advertiser(
        self,
        advertiser: Callable[[], PlaybillWorkspaceAdvertisement],
    ) -> None:
        """Bind the manager-owned advisory Git hook for this process."""

        self._workspace_advertiser = advertiser

    def advertise_workspace(self) -> PlaybillWorkspaceAdvertisement:
        """Refresh advisory refs, or report that this instance has no attachment."""

        if self._workspace_advertiser is None:
            return NOT_ATTACHED_ADVERTISEMENT
        try:
            return self._workspace_advertiser()
        except BaseException:
            return PlaybillWorkspaceAdvertisement(
                status="failed",
                workspace_path=None,
                failure_code="unexpected_failure",
            )

    def proposal_evidence(self) -> ProposalEvidenceStore:
        """Return the immutable non-authoritative proposal/approval evidence store."""

        paths = self._validated_paths(self.root, self.descriptor.storage)
        return ProposalEvidenceStore(paths["exhaust"])

    def review_operational_store(self) -> ReviewOperationalStore:
        """Return the local append-only review observation store.

        This accessor does not initialize the store.  The first successful
        operational append binds its initialization coordinate and generation.
        """

        paths = self._validated_paths(self.root, self.descriptor.storage)
        return ReviewOperationalStore(
            paths["exhaust"],
            instance_id=self.descriptor.instance_id,
        )

    def claim_attestation_evidence_store(self) -> ClaimAttestationEvidenceStore:
        """Return the principal-authored evidence ledger without initializing it."""

        from cruxible_core.playbill.claim_attestation_store import (
            ClaimAttestationEvidenceStore,
        )

        if self._claim_attestation_store is None:
            paths = self._validated_paths(self.root, self.descriptor.storage)
            self._claim_attestation_store = ClaimAttestationEvidenceStore(
                paths["exhaust"],
                instance_id=self.descriptor.instance_id,
            )
        return self._claim_attestation_store

    def accepted_history(self) -> tuple[RecoveredGeneration, ...]:
        """Return the genesis-rooted, replay-verified accepted history."""

        return self._recovered.history

    def accepted_evaluation_time(self, oid: str) -> datetime:
        """Resolve the immutable acceptance instant for one replayed generation."""

        matches = tuple(item for item in self._recovered.history if item.oid == oid)
        if len(matches) != 1:
            raise PlaybillFormatError("evaluation coordinate is outside accepted history")
        generation = matches[0]
        if generation.record is not None:
            try:
                return datetime.strptime(
                    generation.record.candidate.timestamp,
                    "%Y-%m-%dT%H:%M:%S.%fZ",
                ).replace(tzinfo=timezone.utc)
            except ValueError as exc:
                raise PlaybillFormatError("accepted candidate timestamp is malformed") from exc
        author_time, committer_time = self._ledger.commit_timestamps(oid)
        if author_time != committer_time:
            raise PlaybillFormatError("genesis author and committer timestamps disagree")
        return author_time

    def coordinate_for_oid(self, oid: str) -> AcceptedProjectionCoordinate:
        """Resolve one accepted historical OID to its complete verified coordinate."""

        matches = tuple(
            generation for generation in self._recovered.history if generation.oid == oid
        )
        if len(matches) != 1:
            raise PlaybillFormatError("Git OID is not one accepted generation of this instance")
        generation = matches[0]
        return AcceptedProjectionCoordinate(
            instance_id=self.descriptor.instance_id,
            repository_path=str(self._ledger.path.resolve(strict=True)),
            git_object_format=self.descriptor.git_object_format,
            git_oid=generation.oid,
            semantic_root=generation.semantic_root.tagged,
            generation_root=generation.generation_root.tagged,
            compiler=self.descriptor.compiler,
        )

    def generation_for_semantic_root(self, semantic_root: str) -> RecoveredGeneration:
        """Resolve one historical signing root without consulting mutable proposal state."""

        matches = tuple(
            generation
            for generation in self._recovered.history
            if generation.semantic_root.tagged == semantic_root
        )
        if len(matches) != 1:
            raise PlaybillFormatError(
                "semantic root is not one accepted generation of this instance"
            )
        return matches[0]

    def tree_at(self, oid: str) -> dict[str, bytes]:
        """Read an exact Git tree only after proving the OID is accepted history."""

        self.coordinate_for_oid(oid)
        return self._ledger.read_tree(oid)

    def proposal_tree(self, oid: str) -> dict[str, bytes]:
        """Read one proposal commit tree for evidence-bound settlement."""

        return self._ledger.read_tree(oid)

    def resolve_accepted_coordinate(
        self,
        *,
        git_oid: str,
        semantic_root: str,
        generation_root: str,
        compiler_digest: str | None = None,
    ) -> AcceptedProjectionCoordinate:
        """Verify exact triple/compiler correspondence against replayed history."""

        coordinate = self.coordinate_for_oid(git_oid)
        if (
            coordinate.semantic_root != semantic_root
            or coordinate.generation_root != generation_root
        ):
            raise PlaybillFormatError("accepted coordinate triple has mixed members")
        if compiler_digest is not None and coordinate.compiler.rule_digest != compiler_digest:
            raise PlaybillFormatError("accepted coordinate compiler digest is unsupported")
        return coordinate

    def bind_accepted_projection(
        self,
        coordinate: AcceptedProjectionCoordinate,
    ) -> ProjectionHandle:
        """Bind a current serving or retained historical immutable projection."""

        verified = self.resolve_accepted_coordinate(
            git_oid=coordinate.git_oid,
            semantic_root=coordinate.semantic_root,
            generation_root=coordinate.generation_root,
            compiler_digest=coordinate.compiler.rule_digest,
        )
        paths = self._validated_paths(self.root, self.descriptor.storage)
        if verified == self.accepted_coordinate():
            return bind_current_projection(paths["projections"], expected=verified)
        assembler = ProjectionAssembler(
            self._ledger,
            accepted=verified,
            publication_directory=paths["projections"],
            bodies=ContentAddressedBodyStore(paths["cas"]),
            accepted_coordinates_by_sequence=self._accepted_coordinates_by_sequence(),
        )
        request = assembler.request(
            output_staging_directory=paths["projections"] / ".historical-bind"
        )
        manifest_path = paths["projections"] / projection_manifest_name(request)
        return bind_projection(manifest_path, expected=verified)

    def refresh(self, *, witness: WitnessSink | None = None) -> AcceptedProjectionCoordinate:
        """Replay accepted state after activation and repair its serving boundary."""

        paths = self._validated_paths(self.root, self.descriptor.storage)
        self._recovered = recover_instance(
            self._ledger,
            genesis=self._verified_genesis,
            instance_id=self.descriptor.instance_id,
            object_format=self.descriptor.git_object_format,
            compiler=self.descriptor.compiler,
            publication_directory=paths["projections"],
            bodies=ContentAddressedBodyStore(paths["cas"]),
            witness=witness,
            promotion_verifier=self._promotion_verifier,
            query_facts_builder=self._accepted_query_facts,
            checkpoint_directory=self._checkpoint_directory(self.root),
        )
        return self.accepted_coordinate()

    def activation_publisher(
        self,
        *,
        witness: WitnessSink | None = None,
    ) -> ActivationPublisher:
        """Bind PB-D activation to this instance's projection and body stores."""

        paths = self._validated_paths(self.root, self.descriptor.storage)
        return ActivationPublisher(
            self._ledger,
            publication_directory=paths["projections"],
            bodies=ContentAddressedBodyStore(paths["cas"]),
            witness=witness,
            accepted_coordinates_by_sequence=self._accepted_coordinates_by_sequence(),
            checkpoint_directory=self._checkpoint_directory(self.root),
            checkpoint_interval=DEFAULT_CHECKPOINT_INTERVAL,
            genesis=self.descriptor.genesis,
        )

    def prepare_generation(
        self,
        *,
        base: AcceptedProjectionCoordinate,
        candidate_tree: dict[str, bytes],
        candidate: CandidateRecordAnyVersion,
        approvals: tuple[ApprovalSubmission, ...],
        actor_binding: ChangeActorBinding,
        proposal_actor_id: str,
        sequence: int,
    ) -> VerifiedGenerationBundle:
        """Construct one verified generation without exposing the Git ledger to surfaces."""

        return prepare_generation(
            self._ledger,
            base=base,
            candidate_tree=candidate_tree,
            candidate=candidate,
            approval_submissions=approvals,
            bodies=self.body_store(),
            actor_binding=actor_binding,
            proposal_actor_id=proposal_actor_id,
            sequence=sequence,
            promotion_verifier=self._promotion_verifier,
            query_facts_provider=lambda coordinate: self._accepted_query_facts(self, coordinate),
        )

    def assemble_projection(
        self,
        *,
        crash_hook: ProjectionCrashHook | None = None,
    ) -> AssemblerResult:
        """Build and publish the current verified generation for internal serving."""

        assembler = self.projection_assembler()
        staging = assembler.publication_directory / f".stage-{secrets.token_hex(12)}"
        return assembler.assemble(
            assembler.request(output_staging_directory=staging),
            crash_hook=crash_hook,
        )


__all__ = ["DESCRIPTOR_FILE", "PlaybillInstance"]
