"""Shared service layer — the execution contract behind CLI, MCP, and REST/SDK.

Every product operation goes through this package. Callers (CLI commands, MCP
handlers, REST endpoints) are thin wrappers that handle I/O formatting,
permission checks, and protocol-specific concerns.
"""

from cruxible_core.service.analysis import (
    service_analyze_feedback,
    service_analyze_outcomes,
    service_config_compatibility_warnings,
    service_evaluate,
    service_lint,
)
from cruxible_core.service.config_mutations import (
    service_add_constraint,
    service_add_decision_policy,
)
from cruxible_core.service.decisions import (
    service_abandon_decision_record,
    service_create_decision_record,
    service_finalize_decision_record,
    service_get_decision_record,
    service_list_decision_events,
    service_list_decision_records,
)
from cruxible_core.service.execution import (
    service_apply_workflow,
    service_lock,
    service_plan,
    service_propose_workflow,
    service_run,
    service_test,
)
from cruxible_core.service.feedback import (
    service_feedback,
    service_feedback_batch,
    service_get_outcome_profile,
    service_outcome,
)
from cruxible_core.service.groups import (
    derive_review_priority,
    service_get_group,
    service_group_status,
    service_list_groups,
    service_list_resolutions,
    service_propose_group,
    service_resolve_group,
    service_update_trust_status,
)
from cruxible_core.service.lifecycle import (
    service_init,
    service_reload_config,
    service_validate,
)
from cruxible_core.service.mutations import (
    service_add_entities,
    service_add_relationships,
)
from cruxible_core.service.queries import (
    service_describe_query,
    service_get_entity,
    service_get_receipt,
    service_get_relationship,
    service_get_relationship_lineage,
    service_get_trace,
    service_inspect_entity,
    service_list,
    service_list_queries,
    service_list_traces,
    service_query,
    service_sample,
    service_schema,
    service_stats,
)
from cruxible_core.service.server import service_server_info
from cruxible_core.service.snapshots import (
    service_clone_snapshot,
    service_create_snapshot,
    service_list_snapshots,
)
from cruxible_core.service.types import (
    AddConstraintServiceResult,
    AddDecisionPolicyServiceResult,
    AddEntityResult,
    AddRelationshipResult,
    AnalyzeFeedbackResult,
    AnalyzeOutcomesResult,
    ApplyWorkflowResult,
    CanonicalViewResult,
    CloneSnapshotResult,
    ConstraintSuggestion,
    DebugPackage,
    DecisionEventListResult,
    DecisionPolicySuggestion,
    DecisionRecordListResult,
    DecisionRecordServiceResult,
    ExportEdgesResult,
    FeedbackBatchServiceResult,
    FeedbackGroupSummary,
    FeedbackServiceResult,
    GetGroupResult,
    GroupMemberReviewResult,
    InitResult,
    InspectEntityResult,
    InspectNeighborResult,
    LintServiceResult,
    LintSummary,
    ListGroupsResult,
    ListResolutionsResult,
    ListResult,
    LockServiceResult,
    OperationContext,
    OutcomeDecisionPolicySuggestion,
    OutcomeGroupSummary,
    OutcomeProviderFixCandidate,
    OutcomeServiceResult,
    PlanServiceResult,
    PropertyDeltaResult,
    ProposeGroupResult,
    ProposeWorkflowResult,
    ProviderFixCandidate,
    QualityCheckCandidate,
    QueryDefinitionServiceResult,
    QueryParamHints,
    QueryPolicySuggestion,
    QueryServiceResult,
    ReceiptExplanationResult,
    RelationshipLineageResult,
    ReloadConfigResult,
    RenderWikiPageResult,
    RenderWikiResult,
    ResolveGroupResult,
    RunServiceResult,
    ServerInfoServiceResult,
    SnapshotCreateResult,
    SnapshotListResult,
    StatsServiceResult,
    SuppressedProposalMember,
    TestServiceResult,
    TraceListResult,
    TrustAdjustmentSuggestion,
    UncodedFeedbackExample,
    UncodedOutcomeExample,
    ValidateServiceResult,
    WorldOverlayResult,
    WorldPublishResult,
    WorldPullApplyResult,
    WorldPullPreviewResult,
    WorldStatusResult,
)
from cruxible_core.service.views import (
    service_explain_receipt,
    service_export_edges,
    service_inspect_view,
    service_render_wiki,
)
from cruxible_core.service.world import (
    service_create_world_overlay,
    service_publish_world,
    service_pull_world_apply,
    service_pull_world_preview,
    service_world_status,
)

__all__ = [
    # Types
    "AddEntityResult",
    "AddConstraintServiceResult",
    "AddDecisionPolicyServiceResult",
    "AddRelationshipResult",
    "ApplyWorkflowResult",
    "AnalyzeFeedbackResult",
    "AnalyzeOutcomesResult",
    "ConstraintSuggestion",
    "DecisionPolicySuggestion",
    "DecisionEventListResult",
    "DecisionRecordListResult",
    "DecisionRecordServiceResult",
    "DebugPackage",
    "FeedbackBatchServiceResult",
    "FeedbackGroupSummary",
    "FeedbackServiceResult",
    "CloneSnapshotResult",
    "CanonicalViewResult",
    "GetGroupResult",
    "GroupMemberReviewResult",
    "ExportEdgesResult",
    "InspectEntityResult",
    "InspectNeighborResult",
    "InitResult",
    "LockServiceResult",
    "WorldOverlayResult",
    "WorldPublishResult",
    "WorldPullApplyResult",
    "WorldPullPreviewResult",
    "WorldStatusResult",
    "ListGroupsResult",
    "ListResolutionsResult",
    "ListResult",

    "LintServiceResult",
    "LintSummary",
    "OutcomeServiceResult",
    "OutcomeDecisionPolicySuggestion",
    "OutcomeGroupSummary",
    "OutcomeProviderFixCandidate",
    "PlanServiceResult",
    "OperationContext",
    "PropertyDeltaResult",
    "ProposeWorkflowResult",
    "ProviderFixCandidate",
    "QueryPolicySuggestion",
    "QualityCheckCandidate",
    "ProposeGroupResult",
    "QueryDefinitionServiceResult",
    "QueryParamHints",
    "QueryServiceResult",
    "ReceiptExplanationResult",
    "RelationshipLineageResult",
    "ReloadConfigResult",
    "RenderWikiPageResult",
    "RenderWikiResult",
    "ResolveGroupResult",
    "RunServiceResult",
    "ServerInfoServiceResult",
    "SnapshotCreateResult",
    "SnapshotListResult",
    "StatsServiceResult",
    "SuppressedProposalMember",
    "TestServiceResult",
    "TraceListResult",
    "TrustAdjustmentSuggestion",
    "UncodedFeedbackExample",
    "UncodedOutcomeExample",
    "ValidateServiceResult",
    # Execution
    "service_lock",
    "service_world_status",
    "service_publish_world",
    "service_create_world_overlay",
    "service_pull_world_preview",
    "service_pull_world_apply",
    "service_plan",
    "service_apply_workflow",
    "service_propose_workflow",
    "service_run",
    "service_test",
    "service_create_snapshot",
    "service_clone_snapshot",
    "service_list_snapshots",
    "service_explain_receipt",
    "service_export_edges",
    "service_inspect_view",
    "service_render_wiki",
    # Analysis
    "service_evaluate",
    "service_analyze_feedback",
    "service_analyze_outcomes",
    "service_config_compatibility_warnings",
    "service_lint",
    # Feedback
    "service_create_decision_record",
    "service_get_decision_record",
    "service_list_decision_records",
    "service_list_decision_events",
    "service_finalize_decision_record",
    "service_abandon_decision_record",
    "service_feedback",
    "service_feedback_batch",
    "service_get_outcome_profile",
    "service_outcome",
    # Groups
    "derive_review_priority",
    "service_get_group",
    "service_group_status",
    "service_list_groups",
    "service_list_resolutions",
    "service_propose_group",
    "service_resolve_group",
    "service_update_trust_status",
    # Mutations
    "service_add_entities",
    "service_add_relationships",
    # Queries
    "service_get_entity",
    "service_inspect_entity",
    "service_get_receipt",
    "service_get_relationship",
    "service_get_relationship_lineage",
    "service_get_trace",
    "service_add_constraint",
    "service_add_decision_policy",
    "service_init",
    "service_list",
    "service_list_queries",
    "service_list_traces",
    "service_describe_query",
    "service_query",
    "service_reload_config",
    "service_sample",
    "service_schema",
    "service_server_info",
    "service_stats",
    "service_validate",
]
